### ISSUE TITLE
Looks like label printing is broken

### ISSUE THREAD

**Issue by elaynepelz** [jordanbrown0/reg3#205]
Prints the name correctly and changes the size of name correctly, but doesn't print the city at all and doesn't print the number correctly when both are checked to be printed

**Comment by jordanbrown0** [comment]
Had you just enabled printing city and number after having them be disabled?  Maybe it hadn't picked up the changes yet.  (I just fixed that, I think.)  Check again after a minute or so, or refresh the page by clicking the circular-arrow icon.

**Comment by jordanbrown0** [comment]
Badge number was pretty totally broken (printed near microscopic).  Ref #204.

**Comment by jordanbrown0** [comment]
I think this is all addressed.
