### ISSUE TITLE
Make classes listing under admin/classes longer

### ISSUE THREAD

**Issue by elaynepelz** [jordanbrown0/reg3#208]
There is lots of room on the page for more lines of text.  Make the classes listing longer if possible or at least give it a up/down function or up/down page function.  Unless you know what is not there, you have a hard time looking up what is not shown

**Comment by jordanbrown0** [comment]
Yes.  I just added something that will put a line at the bottom that says "more matches" or "all matches shown", but neither of those helps you to see additional lines when you don't know what they are.  I'll have to think about this a bit.
